title: Bob's blog
email: bobwebxx@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Bob's blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bobwebxx.github.io"
github_username:  bobwebxx
remote_theme: pages-themes/minimal@v0.2.0
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme
