title: Bob's blog
email: bobwebxx@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Bob's blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bobwebxx.github.io"
github_username:  bobwebxx
theme: jekyll-theme-minimal
markdown: kramdown
plugins:
  - jekyll-feed
